<?php

namespace Daga\Erp\Services;

use Daga\Erp\Models\ErpBasicProduct;
use Daga\Erp\Models\ErpBasicProductUnit;
use Dagasmart\BizAdmin\Services\AdminService;

/**
 * 产品档案表
 *
 * @method ErpBasicProduct getModel()
 * @method ErpBasicProduct|\Illuminate\Database\Query\Builder query()
 */
class ErpBasicProductService extends AdminService
{
    protected string $modelName = ErpBasicProduct::class;

    public function list(): array
    {
        $list  = $this->listQuery()
            ->when(!is_null($this->request['type']),function($query){
                $query->where('type',$this->request['type']);
            })
            ->paginate(request()->input('perPage', 20));
        $items = $list->items();
        $total = $list->total();
        $res = compact('items', 'total');
        if($res['items']){
            foreach ($res['items'] as $k=>$v){
                $res['items'][$k]['type_as'] = self::type()[$v->type];
                $res['items'][$k]['unit_as'] = self::unit('name','id')[$v->unit_id];
                $res['items'][$k]['sup_as'] = ErpBasicSupplierService::sup_as($v->sup_id);
            }
        }
        return $res;
    }

    public function store($data): bool
    {
        $data['py_code'] =  $data['name'];
        //$data['image'] = $data['image_url'];
        //$data['slider_image'] = $data['slider_image_url'];
        return parent::store($data);
    }

    public function saving(&$data, $primaryKey = ''): void
    {
        $data['py_code'] =  $data['name'];
        //$data['image'] = $data['image_url'];
        //$data['slider_image'] = $data['slider_image_url'];
        parent::saving($data, $primaryKey); // TODO: Change the autogenerated stub
    }

    /**
     * 产品编号生成器
     * @return string
     */
    public static function itemNoGen(): string
    {
        $item_no = ErpBasicProduct::query()->where('mer_id',admin_user()->mer_id)->orderBy('id', 'desc')->value('item_no') ?? 0;
        return date('Ymd') . admin_user()->mer_id . str_pad(intval(mb_substr($item_no,-8)) + 1, 8, '0', STR_PAD_LEFT);
    }

    /**
     * 产品单位
     * @param string $column
     * @param string $key
     * @return array
     */
    public static function unit(string $column, string $key): array
    {
        $data = ErpBasicProductUnit::query()
            ->when(admin_user()->mer_id, function ($query){
                $query->where('mer_id',admin_user()->mer_id);
            })
            ->pluck($column, $key)->toArray();
        return is_null($data) ? [0 => '暂无单位'] : $data;
    }

    public static function type(): array
    {
        return ErpBasicProduct::TYPE;
    }

    public static function supplier():array
    {
        return ErpBasicSupplierService::pluck('sup_name', 'id');
    }

    public static function product(): array
    {
        return ErpBasicProduct::query()->select(['name as name','name as label','item_no as value','item_no','type','unit_id','id'])->get()->toArray();
    }

    public function supApi($sup_id): array
    {
        $sup_id = $sup_id ?: null;
        $list  = $this->listQuery()
            ->when(!is_null($sup_id),function($query,$sup_id){
                $query->where('sup_id', $sup_id);
            })
            ->paginate(request()->input('perPage', 20));
        $items = $list->items();
        $total = $list->total();
        $res = compact('items', 'total');
        if($res['items']){
            foreach ($res['items'] as $k=>$v){
                $res['items'][$k]['type_as'] = self::type()[$v['type']];
                $res['items'][$k]['unit_as'] = self::unit('name','id')[$v['unit_id']];
                $res['items'][$k]['sup_as'] = $v['sup_id'] ? self::supplier()[$v['sup_id']] : [];
            }
        }
        return $res;
    }


}
