<?php
namespace DagaSmart\Erp\Services;

use DagaSmart\Erp\Models\ErpBasicDepos;

/**
 * 仓库表
 *
 * @method ErpBasicDepos getModel()
 * @method ErpBasicDepos|\Illuminate\Database\Query\Builder query()
 */
class ErpBasicDeposService extends AdminService
{
    protected string $modelName = ErpBasicDepos::class;

    public function saving(&$data, $primaryKey = ''): void
    {
        if(isset($data['depos_images_url'])){
            $data['depos_images'] = $data['depos_images_url'];
        }
        parent::saving($data, $primaryKey); // TODO: Change the autogenerated stub
    }
}
