<?php

namespace Daga\Erp\Services;

use Daga\Erp\Models\ErpBasicProductCate;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Dagasmart\BizAdmin\Services\AdminService;

/**
 * 产品分类表
 *
 * @method ErpBasicProductCate getModel()
 * @method ErpBasicProductCate|\Illuminate\Database\Query\Builder query()
 */
class ErpBasicProductCateService extends AdminService
{
    protected string $modelName = ErpBasicProductCate::class;

    public function list(): array
    {
        //request()->orderBy = 'sort';
        //request()->orderDir = 'asc';
        $this->request->orderBy = 'sort';
        $this->request->orderDir = 'asc';
        if($parentId = $this->request['parent_id']){//存在父级传参时，删除该参数
            unset($this->request['parent_id']);
        }
        $res = $this->listQuery()
            ->when($parentId, function ($query,$parentId){
                $query->whereIn('id', $this->cteWith($parentId));
            })
            ->paginate(request('perPage', 20))->toArray();
        $res['data'] = array2tree($res['data']);//树形结构
        return $res;
    }

    /**
     * 分类父子id集合数组
     * @param $id
     * @return array
     */
    public function cteWith($id): array
    {
        $sql = "WITH RECURSIVE CTE AS (
                    WITH RECURSIVE CTE_CHILD AS (
                                SELECT id, parent_id
                                FROM erp_basic_product_cate
                                WHERE id = ?
                                UNION
                                SELECT c.id, c.parent_id
                                FROM erp_basic_product_cate c
                                INNER JOIN CTE_CHILD d ON d.id = c.parent_id
                        )
                        SELECT id,parent_id FROM CTE_CHILD
                    UNION
                    SELECT c.id, c.parent_id
                    FROM erp_basic_product_cate c
                    INNER JOIN CTE d ON d.parent_id = c.id
                )
                SELECT id FROM CTE";
        $res = DB::select($sql,[$id]);
        return $res ? array_column($res,'id') : [];
    }

    public function demo(): array
    {
        return ['items' => $this->getTree()];
    }

    public function getTree(): array
    {
        $list = $this->query()->whereIn('id',[1,2])->orderBy('sort')->get()->toArray();
        return array2tree($list);
    }

    public function saving(&$data, $primaryKey = ''): void
    {
        $data['parent_id'] = $data['parent_id'] ?: 0; //当父级ID为空时设置0
        parent::saving($data, $primaryKey); // TODO: Change the autogenerated stub
    }


    public function treeOptions(): array
    {
        $list = $this->query()
            ->select(['id','parent_id','cate_name as label','id as value'])
            ->when(request()->id,function ($query){
                $query->where('id','!=',request()->id);
            })
            ->when(admin_user()->mer_id,function ($query){
                $query->where('mer_id', admin_user()->mer_id);
            })
            ->orderBy('sort')
            ->get()
            ->toArray();
        return $list ? array2tree($list) : [];
    }


}
