<?php

namespace Daga\Erp\Services;

use Daga\Erp\ErpServiceProvider;
use Daga\Erp\Models\ErpBasicSupplier;
use Daga\Erp\Models\ErpPurchaseOrder;
use Dagasmart\BizAdmin\Services\AdminService;

/**
 * 采购订单表
 *
 * @method ErpPurchaseOrder getModel()
 * @method ErpPurchaseOrder|\Illuminate\Database\Query\Builder query()
 */
class ErpPurchaseOrderService extends AdminService
{
    protected string $modelName = ErpPurchaseOrder::class;

    public function list(): array
    {
        $this->request['mer_id'] = admin_user()->mer_id;
        return parent::list(); // TODO: Change the autogenerated stub
    }

    public function saving(&$data, $primaryKey = ''): void
    {
        $data['user_id'] = admin_user()->id;
        $data['mer_id'] = admin_user()->mer_id;
        //admin_abort('234234234');
        parent::saving($data, $primaryKey); // TODO: Change the autogenerated stub
    }

    /**
     * 采购订单编号生成器
     * @param string $prefix
     * @return string
     */
    public static function itemNoGen(string $prefix = ''): string
    {
        return ErpServiceProvider::itemNoGen($prefix);
    }

    public static function supplier($column, $key): array
    {
        return ErpBasicSupplierService::pluck($column, $key);
    }

    public static function product(): array
    {
        return ErpBasicProductService::product();
    }

    public static function stateOption($isEdit=true, $userId=0, $value=0): array
    {
        $data = [];
        if(!$isEdit || intval($userId) == admin_user()->id){
            return [['label'=>'提交申请', 'value'=>0, 'disabled'=> $isEdit]];
        }
        $data[] = ['label'=>'待审中', 'value'=>0, 'level'=>'info', 'disabled'=> $isEdit];
        $data[] = ['label'=>'已审核', 'value'=>1, 'level'=>'info', 'disabled'=> !$isEdit];
        $data[] = ['label'=>'采购中', 'value'=>2, 'level'=>'info', 'disabled'=> !$isEdit];
        $data[] = ['label'=>'已完成', 'value'=>3, 'disabled'=> !$isEdit];
        $data[] = ['label'=>'已驳回', 'value'=>-1, 'disabled'=> !$isEdit];
        $data[] = ['label'=>'已退货', 'value'=>-2, 'disabled'=> !$isEdit];
        return $data;
    }

    public static function auditOption(): array
    {
        return [
            ['label'=>'通过', 'value'=>1],
            ['label'=>'不通过', 'value'=>1],
        ];

    }

    public static function type(): array
    {
        return ErpBasicProductService::type();
    }

    public static function unit(): array
    {
        return ErpBasicProductService::unit('name', 'id');
    }

}
